---
- block:
  - debug:
      msg: "Stop the QMLPPIB"
  
  - name: "Install httpd and php packages"
    package:
        name:
          - "httpd"
          - "php"
        state: present
 
  - name: "copy code from GitHub"
    get_url:
        url: https://raw.githubusercontent.com/Shashikant17/ansible_task_for_httpdserver/main/index.php
        dest: "/var/www/html/index.php"
 
  - name: "Start httpd services"
    service:
        name: httpd
        state: started

  - debug:
      msg: "Successfully Stop the QMLPPIB "
  
  tags:
    - A1.2