- name: The same as play15.yml, but NOT IDEMPOTENT.
  hosts: localhost
  gather_facts: false
  vars:
    rootLoggerAppender: bla
  tasks:

    - lineinfile:
        path: log4j.properties
#       regexp: '^(log4j\.rootLogger=.*?)(, {{ rootLoggerAppender }})?$'  # idempotent
        regexp: '^(log4j\.rootLogger=.*)$'
        line: '\1, {{ rootLoggerAppender }}'
        backrefs: true

# -log4j.rootLogger=WARN, memory, servlet
# +log4j.rootLogger=WARN, memory, servlet, bla

# -log4j.rootLogger=WARN, memory, servlet, bla
# +log4j.rootLogger=WARN, memory, servlet, bla, bla
