- name: Default state is present.
  hosts: localhost
  gather_facts: false
  vars:
    my_lines:
      - line: myfilecontent
        state: absent
      - line: mynewfilecontent
        state: present
  tasks:
    - lineinfile:
        path: files-5/test.conf
        create: true
        line: "{{ item.line }}"
        state: "{{ item.state }}"
      loop: "{{ my_lines }}"

# +mynewfilecontent

- hosts: localhost
  gather_facts: false
  vars:
    my_lines:
      - line: myfilecontent
        state: absent
      - line: mynewfilecontent
  tasks:
    - lineinfile:
        path: files-5/test.conf
        create: yes
        line: "{{ item.line }}"
        state: "{{ item.state|default('present') }}"
      loop: "{{ my_lines }}"

# +mynewfilecontent

- hosts: localhost
  gather_facts: false
  vars:
    my_lines:
      - line: myfilecontent
        state: absent
      - line: mynewfilecontent
  tasks:
    - lineinfile:
        path: files-5/test.conf
        create: yes
        line: "{{ item.line }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ my_lines }}"

# +mynewfilecontent

# Ansible add a line in file
# https://stackoverflow.com/questions/56801517/ansible-add-a-line-in-file/
