- hosts: localhost
  gather_facts: no
  tasks:

    - package_facts:
      tags: always

    - debug:
        msg: "{{ ansible_facts.packages.keys()|list }}"
      tags: t1

    - debug:
        msg: "{{ ansible_facts.packages }}"
      tags: t2
