- hosts: localhost
  gather_facts: false

  vars:
    IP_server:
      - 10.1.0.61
      - 10.1.0.62
      - 10.1.0.99

  tasks:
    - command: "ping -c 1 {{ item }}"
      register: server_ok
      ignore_errors: yes
      loop: "{{ IP_server }}"
    - debug:
        msg: "{{ server_ok.results|
                 selectattr('rc', 'eq', 0)|
                 map(attribute='item')|
                 list }}"

# TASK [command] ******************************************************************
# changed: [localhost] => (item=10.1.0.61)
# changed: [localhost] => (item=10.1.0.62)
# failed: [localhost] (item=10.1.0.99) => changed=true 
#   ansible_loop_var: item
#   cmd:
#   - ping
#   - -c
#   - '1'
#   - 10.1.0.99
#   delta: '0:00:03.078826'
#   end: '2021-02-25 10:50:17.192211'
#   item: 10.1.0.99
#   msg: non-zero return code
#   rc: 1
#   start: '2021-02-25 10:50:14.113385'
#   stderr: ''
#   stderr_lines: <omitted>
#   stdout: |-
#     PING 10.1.0.99 (10.1.0.99) 56(84) bytes of data.
#     From 10.1.0.27 icmp_seq=1 Destination Host Unreachable
#   
#     --- 10.1.0.99 ping statistics ---
#     1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
#   stdout_lines: <omitted>
# ...ignoring
# 
# TASK [debug] ********************************************************************
# ok: [localhost] => 
#   msg:
#   - 10.1.0.61
#   - 10.1.0.62
