- hosts: localhost
  gather_facts: false
  tasks:

    - debug:
        var: item
      loop:
        - [1,2]
        - [3,4]

#  item:
#    - 1
#    - 2
#  item:
#    - 3
#    - 4
                  
      
    - debug:
        var: item
      with_items:
        - [1,2]
        - [3,4]

#  item: 1
#  item: 2
#  item: 3
#  item: 4
