- hosts: localhost
  gather_facts: false
  vars:
    _hosts: [
        {
            "address": "host1.local",
            "cluster": {
                "name": "RED"
            }
        },
        {
            "address": "host2.local",
            "cluster": {
                "name": "RED"
            }
        },
        {
            "address": "host3.local",
            "cluster": {
                "name": "GREEN"
            }
        },
        {
            "address": "host4.local",
            "cluster": {
                "name": "BLUE"
            }
        }]
  tasks:
    - set_fact:
        hpc: "{{ hpc|default({})|combine({item.0: item.1|length}) }}"
      loop: "{{ _hosts|groupby('cluster.name') }}"
    - debug:
        var: hpc

#  hpc:
#    BLUE: 1
#    GREEN: 1
#    RED: 2
