---
- name: Destroy VM
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: no
    datacenter: "{{ datacenter }}"
    folder: "{{ folder }}"
    name: "{{ vm_name }}"
    state: absent
  register: destroy_result

- name: Fail if VM destroy failed
  fail:
    msg: "Failed to destroy VM {{ vm_name }}"
  when: destroy_result.failed