- hosts: localhost
  gather_facts: false
  tasks:
    - command: hostname
      register: result
      delegate_to: "{{ item }}"
      loop: [test_11, test_12, test_13]
    - debug:
        msg: "{{ result.results|map(attribute='stdout')|list }}"

# ok: [localhost] =>
#   msg:
#     - test_11
#     - test_12
#     - test_13
