# Use a lightweight Alpine Linux image with Nginx web server
FROM nginx:alpine

# Copy the nginx.conf file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# Copy all HTML files from the current directory to the Nginx web root directory
COPY *.html /usr/share/nginx/html/

# Expose port 80 for incoming traffic
EXPOSE 80

# Start the Nginx web server
CMD ["nginx", "-g", "daemon off;"]


vi nginx.conf
=============

user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    include /etc/nginx/sites-enabled/*;

server {

        listen 80;

        server_name localhost;

        root /usr/share/nginx/html;

        index shadefinder.html;

}

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
