---
- hosts: all
  tasks:

    - name: Creates directory
      file:
        path: /root/ansible/
        state: directory
        #owner: www-data
        #group: www-data
        #mode: 0775
        recurse: yes
    - name: Create a file
      file:
        path: /root/ansible/abc.txt
        state: touch
    - name: line insert
      lineinfile:
        path: /root/ansible/abc.txt
        line: 'Added Line 2'
        insertafter: Added Line 1


---
- hosts: linux
  tasks:

    - name: Creates directory
      file:
        path: /root/ansible/
        state: directory
        recurse: yes
      register: dir
    - debug: var=dir

    - name: Create a file
      file:
        path: /root/ansible/abc.txt
        state: touch
      register: file
    - debug: var=file


    - name: line insert
      lineinfile:
        path: "/root/ansible/abc.txt"
        line: "{{ item }}"
#        insertbefore: BOF
#        insertafter: This is the 3rd line
        state: present
      register: insert
      with_items:
        - 'This is the 4th line'
        - 'This is the 5th line'
        - 'This is the 6th line'

