- hosts: localhost
  gather_facts: false
  vars:
    kids:
    - John
    - Shara
    - David
    fruits:
    - Banana
    - Mango
    - Orange
    - Peach
    - Pineapple
    - Watermelon
    - Avocado
    - Cherries
  tasks:
    - set_fact:
        _dict: "{{ dict(kids|zip(_values)) }}"
      vars:
        _batch: "{{ fruits|length|int / kids|length|int }}"
        _values: "{{ fruits|batch(_batch|float|round)|list }}"
    - debug:
        var: _dict

#  _dict:
#    David:
#    - Avocado
#    - Cherries
#    John:
#    - Banana
#    - Mango
#    - Orange
#    Shara:
#    - Peach
#    - Pineapple
#    - Watermelon
