---
- example: 'ExecStart={ path=/home/bin/ide-1.0.1 ; argv[]=/home/bin/ide-1.0.1 start }'
  getval: '(?P<property>\S+)={\s*(?P<key1>\S+)=(?P<val1>\S+)\s*;\s*(?P<key2>\S+)=(?P<val2>\S+)\s(?P<state>\S+)\s*}'
  result:
    "{{ property }}":
      "{{ key1 }}": "{{ val1 }}"
      "{{ key2 }}": "{{ val2 }}"
      state: "{{ state }}"
