- hosts: localhost
  gather_facts: false
  tasks:
    - meta: end_play
      when: condition|default(false)|bool
    - debug:
        msg: Start play 1

- hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: Start play 2
